Implement ToolWindow
zakodium-oss/react-science pull request #735
Opened 2024-06-12 15:16 UTC by wadjih-bencheikh18

closes : https://github.com/zakodium-oss/react-science/issues/243

2024-07-11 19:02 UTC, wadjih-bencheikh18 commented
@stropitek this PR is ready to merge

2024-07-12 11:49 UTC, stropitek reviewed
In a real application, the accordion panels will be rendered within a SplitPane, but the toolbar will be rendered some place else in the layout (this part has a fixed size).

So I think the API I proposed is not going to work, because it forces both to be rendered together.

Can you just focus on a simple stateless component that renders the big toolbar buttons and remove the rest of the code?

The component should:
- Have a good name (I'm thinking `PanelToolbar` + `PanelToolbar.Item`, but not convinced)
- Be able to render the items with a prop that makes it look selected / unselected.

2024-07-16 20:13 UTC, wadjih-bencheikh18 commented
> Can you just focus on a simple stateless component that renders the big toolbar buttons and remove the rest of the code?

Is it worth to create a component for that? isn't it enough to create just story for it. because the implementation is simply div with toolbar items inside.

2024-07-18 06:54 UTC, stropitek commented
> Is it worth to create a component for that? isn't it enough to create just story for it. because the implementation is simply div with toolbar items inside.

Indeed if we don't need custom style and just layout with existing components then a story is enough.

2024-08-13 08:18 UTC, stropitek commented on src/components/accordion/Accordion.tsx
> +      key={title}
```suggestion
```

2024-08-13 08:18 UTC, stropitek commented on src/components/toolbar/Toolbar.tsx
> +    Omit<ButtonProps, 'onClick' | 'tooltipProps'> {
I would rather `Pick` some props that we know we need, rather than omit.

Each props that we pick should have a corresponding story.

2024-08-13 08:18 UTC, stropitek commented on stories/components/panel-toolbar.stories.tsx
> +              fill
Those props should be part of the `Toolbar` component. I don't think we should be able to mix different styles of buttons in a toolbar.

When we do we should have stories showing what purpose this mixing serves.

2024-08-19 06:56 UTC, stropitek requested changes
The non-minimal version of the toolbar does not seem to be correct.

Screenshot from storybook:
![CleanShot 2024-08-19 at 08 54 52](https://github.com/user-attachments/assets/a9f6db5b-4bb8-4dbf-898b-5d90d244fb79)

Screenshot from blueprintjs documentation:
![CleanShot 2024-08-19 at 08 55 46](https://github.com/user-attachments/assets/e1f1fb9d-2fac-49e8-8015-deda1cd18d8a)

2024-08-19 06:56 UTC, stropitek commented on src/components/toolbar/Toolbar.tsx
> +  tag?: ReactNode;
Can you use `Pick<ButtonProps, ...>` for all the properties that are forwarded to the `Button` component?

2024-08-20 09:29 UTC, stropitek reviewed
Please review any missing controls (like `minimal` and `vertical`) in [the control story](https://243-create-toolwindow-compon.react-science.pages.dev/stories/?path=/story/components-toolbar--control) and add them to the story.

---

Please write your commit message for this PR. It needs to mention the breaking change for the `Toolbar` component, which now renders differently by default (without `minimal` set to `true`).

2024-08-20 09:29 UTC, stropitek commented on src/components/button/Button.tsx
> +            <div>
Can't this be a fragment?

2024-08-20 09:29 UTC, stropitek commented on src/components/toolbar/Toolbar.tsx
> -  className?: string;
Why have you removed this prop?

2024-08-20 09:29 UTC, stropitek commented on stories/components/panel-toolbar.stories.tsx
Can you move this story with the other toolbar stories?

2024-08-20 09:29 UTC, stropitek commented on stories/components/toolbar.stories.tsx
> +    alignText: 'center',
Is `alignText` really a prop of toolbar? What does it do?

2024-08-20 09:29 UTC, stropitek commented on stories/components/toolbar.stories.tsx
> +    fill: false,
What does it do? When I change it in the story it does not have any effect.

2024-08-20 09:29 UTC, stropitek commented on stories/components/toolbar.stories.tsx
> +            tag: (itemProps.id.startsWith('credit-card') && 1) || null,
```suggestion
            tag: itemProps.id.startsWith('credit-card') ? 1 : null,
```

2024-09-28 15:51 UTC, wadjih-bencheikh18 commented
> Please review any missing controls (like `minimal` and `vertical`) in [the control story](https://243-create-toolwindow-compon.react-science.pages.dev/stories/?path=/story/components-toolbar--control) and add them to the story.

Improved

2024-09-30 07:15 UTC, stropitek reviewed
Blueprint icons come in 2 sizes: 16px and 20px.

It would make sense that the large version of the component also shows the larger icons, no?

Can you do that so that we can see if it looks better?

2024-09-30 07:15 UTC, stropitek commented on stories/components/toolbar.stories.tsx
> +    minimal: false,
Can you make this true since it used to be the default and we actually mostly want to use the minimal version.

2024-10-01 13:17 UTC, wadjih-bencheikh18 commented
> It would make sense that the large version of the component also shows the larger icons, no?

Yes. Blueprint Button use the small icon in all cases https://blueprintjs.com/docs/#core/components/buttons

2024-10-01 15:48 UTC, wadjih-bencheikh18 commented
> Can you do that so that we can see if it looks better?

You can take a look.
For the toolbar icons they can be **string** (blueprint native icons) or **component** or **text** 
I tried to check all these cases

2024-10-02 15:42 UTC, stropitek commented
OK let's go with the larger icons.

I noticed that when you use the vertical version with the `fill` option to `true`, it fills the horizontal space instead of the vertical space. Can you check if it can be changed to be like https://blueprintjs.com/docs/#core/components/button-group ?

2024-10-02 23:21 UTC, wadjih-bencheikh18 commented
> I noticed that when you use the vertical version with the `fill` option to `true`, it fills the horizontal space instead of the vertical space. Can you check if it can be changed to be like https://blueprintjs.com/docs/#core/components/button-group ?

It's working now

2024-10-03 08:04 UTC, stropitek approved these changes
Do you see any breaking changes that need to be documented?

Please provide a commit message that summarises the API changes.

2024-10-03 14:29 UTC, wadjih-bencheikh18 commented
> Do you see any breaking changes that need to be documented?

Only changing the default minimal in toolbar which I added a commit for it

2024-10-03 15:18 UTC, merged

2024-10-15 19:58 UTC, targos commented
This commit broke popover items on toolbars: https://github.com/zakodium-oss/react-science/issues/773