feat: virtualize table rows
zakodium-oss/react-science pull request #796
Opened 2024-12-02 15:25 UTC by stropitek

- **fix: correct sticky header control in control story**
- **wip: working prototype**
- **feat: change API of custom renderRowTr to make it work seemlessly with virtualization**
- **docs: document table props and add custom tr render storybook example**

2024-12-02 15:56 UTC, stropitek commented
There is a change in how borders are displayed when `striped` and `bordered` is combined.

I prefer the new one:

Before:
![CleanShot 2024-12-02 at 16 55 57](https://github.com/user-attachments/assets/6cd4291e-a2be-4c72-9042-de93735c112e)

After:
![CleanShot 2024-12-02 at 16 55 25](https://github.com/user-attachments/assets/12fd22bb-831f-451d-b872-f54c50f3b73c)

2024-12-02 16:29 UTC, targos commented
I don't see the difference, even from afar where I see both at the same time.

2024-12-03 07:52 UTC, targos requested changes
stickyHeader doesn't work after some scrolling with the Virtualized and Custom Tr Render stories.

2024-12-03 07:52 UTC, targos commented on src/components/table/table_root.tsx
> +   * it is recommended that all cells have a fixed width.
```suggestion
   * it is recommended that all columns have a fixed width.
```

2024-12-03 08:32 UTC, stropitek commented
> I don't see the difference, even from afar where I see both at the same time.

The second one has "borders" (technically it's a `box-shadow`) in between rows.

2024-12-03 10:28 UTC, targos approved these changes

2024-12-03 10:35 UTC, merged